std_msgs/Header     header
uint32              end_sel       # 0 = left, 1 = right, 2 = both
bool                control       # false: 不控制, true: 控制
---
std_msgs/Header     res_header
uint8               exec_result   # 0: success, 1: failed 