if(NOT DEFINED OpenCV_LIBS)
    set(OpenCV_LIBS opencv::opencv)
endif()
if(NOT DEFINED OpenCV_VERSION_MAJOR)
    set(OpenCV_VERSION_MAJOR 4)
endif()
if(NOT DEFINED OpenCV_VERSION_MINOR)
    set(OpenCV_VERSION_MINOR 10)
endif()
if(NOT DEFINED OpenCV_VERSION_PATCH)
    set(OpenCV_VERSION_PATCH 0)
endif()
