# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agibotdds_test_pub_serv_messages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='agibotdds_test_pub_serv_messages.proto',
  package='agibot.genie.messages.internal',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n#agibotdds_test_pub_serv_messages.proto\x12\x18agibot.genie.messages.internal\"\x19\n\x06\x41ppReq\x12\x0f\n\x07req_num\x18\x01 \x02(\x05\"t\n\tAppStatus\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0f\n\x07process\x18\x02 \x02(\t\x12\x0b\n\x03pid\x18\x03 \x02(\r\x12\x16\n\x0elast_heartbeat\x18\x04 \x02(\x04\x12\x11\n\ttimestamp\x18\x05 \x02(\x04\x12\x10\n\x08interval\x18\x06 \x02(\x05')
)




_APPREQ = _descriptor.Descriptor(
  name='AppReq',
  full_name='agibot.genie.messages.internal.AppReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='req_num', full_name='agibot.genie.messages.internal.AppReq.req_num', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=90,
)


_APPSTATUS = _descriptor.Descriptor(
  name='AppStatus',
  full_name='agibot.genie.messages.internal.AppStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='agibot.genie.messages.internal.AppStatus.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='process', full_name='agibot.genie.messages.internal.AppStatus.process', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pid', full_name='agibot.genie.messages.internal.AppStatus.pid', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_heartbeat', full_name='agibot.genie.messages.internal.AppStatus.last_heartbeat', index=3,
      number=4, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='agibot.genie.messages.internal.AppStatus.timestamp', index=4,
      number=5, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='interval', full_name='agibot.genie.messages.internal.AppStatus.interval', index=5,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=208,
)

DESCRIPTOR.message_types_by_name['AppReq'] = _APPREQ
DESCRIPTOR.message_types_by_name['AppStatus'] = _APPSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AppReq = _reflection.GeneratedProtocolMessageType('AppReq', (_message.Message,), {
  'DESCRIPTOR' : _APPREQ,
  '__module__' : 'agibotdds_test_pub_serv_messages_pb2'
  # @@protoc_insertion_point(class_scope:agibot.genie.messages.internal.AppReq)
  })
_sym_db.RegisterMessage(AppReq)

AppStatus = _reflection.GeneratedProtocolMessageType('AppStatus', (_message.Message,), {
  'DESCRIPTOR' : _APPSTATUS,
  '__module__' : 'agibotdds_test_pub_serv_messages_pb2'
  # @@protoc_insertion_point(class_scope:agibot.genie.messages.internal.AppStatus)
  })
_sym_db.RegisterMessage(AppStatus)


# @@protoc_insertion_point(module_scope)
