std_msgs/Header     req_header
uint32              arm_sel       # 0 = left, 1 = right, 2 = both
bool                control       # false: 不控制机械臂, true: 控制机械臂
---
std_msgs/Header     res_header
uint8               exec_result   #  0: success, 1: failed