std_msgs/Header     header
uint32              arm_sel         # 0 = left, 1 = right, 2 = both
float32[]           joint_states    # 关节初始化位置
bool                block           # true: sync, false: async
---
std_msgs/Header     res_header
uint8               exec_result     # 0: success, 1: failed 