std_msgs/Header     header
uint8               work_mode        # 0: uninit, 1: EOL, 2: Debug, 3: Test, 4: DataAcq, 5: Inference, 6: SDK, 7: OTA, 8: DEMO
---
std_msgs/Header     res_header
uint8               exec_result   # 0: success, 1: failed 