std_msgs/Header     header
uint8               ctrl_mode     # 0 = whole body, 1 = duel arm, 2 = left arm, 3 = right arm
---
std_msgs/Header     res_header
uint8               exec_result   # 0: success, 1: failed 