std_msgs/Header     header
string              task_uuid   # 任务执行编号
---
std_msgs/Header     res_header
uint32              req_result
uint32              ret_code    # 0:成功，其他失败
uint32              task_uuid   # 任务编号(由底盘生成）