# /hal/map/get_map
#根据指定map id 获取地图详细信息
std_msgs/Header header
int32 map_id         # map id
---
int32 x             #地图原点x
int32 y             #地图原点y
int32 width         #地图 宽
int32 height        #地图 高
string name    #地图ming
string data        #地图图片，以base64编码的png图片，png背景为透明
int32 error_code      #错误码 0:成功