from genie_msgs.srv._agv_cancel_task import AGVCancelTask  # noqa: F401
from genie_msgs.srv._agv_collision_level import AGVCollisionLevel  # noqa: F401
from genie_msgs.srv._agv_emerg_stop import AGVEmergStop  # noqa: F401
from genie_msgs.srv._agv_get_map import AGVGetMap  # noqa: F401
from genie_msgs.srv._agv_map_delete import AGVMapDelete  # noqa: F401
from genie_msgs.srv._agv_map_list import AGVMapList  # noqa: F401
from genie_msgs.srv._agv_mapping_control import AGVMappingControl  # noqa: F401
from genie_msgs.srv._agv_mode_control import AGVModeControl  # noqa: F401
from genie_msgs.srv._agv_new_task import AGVNewTask  # noqa: F401
from genie_msgs.srv._agv_set_color import AGVSetColor  # noqa: F401
from genie_msgs.srv._agv_switch_map import AGVSwitchMap  # noqa: F401
from genie_msgs.srv._arm_cal import ArmCal  # noqa: F401
from genie_msgs.srv._arm_collision_level import ArmCollisionLevel  # noqa: F401
from genie_msgs.srv._arm_control import ArmControl  # noqa: F401
from genie_msgs.srv._arm_emerg_stop import ArmEmergStop  # noqa: F401
from genie_msgs.srv._arm_eol import ArmEOL  # noqa: F401
from genie_msgs.srv._arm_fault_clear import ArmFaultClear  # noqa: F401
from genie_msgs.srv._arm_get_collision_level import ArmGetCollisionLevel  # noqa: F401
from genie_msgs.srv._arm_go_pose import ArmGoPose  # noqa: F401
from genie_msgs.srv._arm_init_pose import ArmInitPose  # noqa: F401
from genie_msgs.srv._arm_restart import ArmRestart  # noqa: F401
from genie_msgs.srv._body_init_pose import BodyInitPose  # noqa: F401
from genie_msgs.srv._body_pose import BodyPose  # noqa: F401
from genie_msgs.srv._call_connect import CallConnect  # noqa: F401
from genie_msgs.srv._end_cal import EndCal  # noqa: F401
from genie_msgs.srv._end_control import EndControl  # noqa: F401
from genie_msgs.srv._end_emerg_stop import EndEmergStop  # noqa: F401
from genie_msgs.srv._end_init_pose import EndInitPose  # noqa: F401
from genie_msgs.srv._feat_get_ctrl_mode import FeatGetCtrlMode  # noqa: F401
from genie_msgs.srv._feat_set_ctrl_mode import FeatSetCtrlMode  # noqa: F401
from genie_msgs.srv._feat_set_work_mode import FeatSetWorkMode  # noqa: F401
from genie_msgs.srv._feat_shut_down import FeatShutDown  # noqa: F401
from genie_msgs.srv._force_cal import ForceCal  # noqa: F401
from genie_msgs.srv._force_info import ForceInfo  # noqa: F401
from genie_msgs.srv._force_init import ForceInit  # noqa: F401
from genie_msgs.srv._force_zero_cal import ForceZeroCal  # noqa: F401
from genie_msgs.srv._head_init_pose import HeadInitPose  # noqa: F401
from genie_msgs.srv._language import Language  # noqa: F401
from genie_msgs.srv._mocap_mapping import MocapMapping  # noqa: F401
from genie_msgs.srv._motion_control_request import MotionControlRequest  # noqa: F401
from genie_msgs.srv._motion_stop_request import MotionStopRequest  # noqa: F401
from genie_msgs.srv._multi_talk_request import MultiTalkRequest  # noqa: F401
from genie_msgs.srv._navigate_pose import NavigatePose  # noqa: F401
from genie_msgs.srv._noitom_calibrate import NoitomCalibrate  # noqa: F401
from genie_msgs.srv._noitom_get_info import NoitomGetInfo  # noqa: F401
from genie_msgs.srv._noitom_reconnect import NoitomReconnect  # noqa: F401
from genie_msgs.srv._noitom_reset import NoitomReset  # noqa: F401
from genie_msgs.srv._noitom_restart import NoitomRestart  # noqa: F401
from genie_msgs.srv._noitom_set_freq import NoitomSetFreq  # noqa: F401
from genie_msgs.srv._pico_reconnect import PicoReconnect  # noqa: F401
from genie_msgs.srv._re_localization import ReLocalization  # noqa: F401
from genie_msgs.srv._record_control import RecordControl  # noqa: F401
from genie_msgs.srv._remote_set_ctrl_mode import RemoteSetCtrlMode  # noqa: F401
from genie_msgs.srv._set_force_protect import SetForceProtect  # noqa: F401
from genie_msgs.srv._set_wifi import SetWifi  # noqa: F401
from genie_msgs.srv._teleop_mode import TeleopMode  # noqa: F401
from genie_msgs.srv._tts_request import TtsRequest  # noqa: F401
from genie_msgs.srv._wbc_reset import WbcReset  # noqa: F401
from genie_msgs.srv._wbc_set_ctrl_mode import WbcSetCtrlMode  # noqa: F401
from genie_msgs.srv._wbc_start import WbcStart  # noqa: F401
from genie_msgs.srv._wbc_stop import WbcStop  # noqa: F401
