std_msgs/Header     header
int32               cali_cmd       # 1: 标定遥设备数据, 2: 停止标定
bool                block          # 是否阻塞
---
std_msgs/Header     res_header
uint8               exec_result   # 0: success, 1: failed 