mode: COPILOT
# two preprocess config examples:
img_preproc [
    {
        pos: hand_left #需要打开的摄像头名称，配置到的才会打开
        FrameRate: 25 #需要的帧率
        crop { #预处理裁剪
            enable: true #true为打开，false为关闭
            l: 0 #裁剪的左边界
            t: 0 #裁剪的上边界
            r: 424 #裁剪的右边界
            b: 240 #裁剪的下边界
        }
        resize { #预处理改变大小
            enable: true #开关
            w: 212 #withd像素
            h: 120 #height像素
        }
        permute { #提供给需要通道的转换的场景，默认[0,1,2]为RGB通道顺序，如[2,1,0]则为BGR
            enable: false
            order1: 0
            order2: 1
            order3: 2
        }
    },
    {
        pos: hand_right #需要打开的摄像头名称，配置到的才会打开
        FrameRate: 30 #需要的帧率
        crop { #预处理裁剪
            enable: false #true为打开，false为关闭
            l: 0 #裁剪的左边界
            t: 0 #裁剪的上边界
            r: 424 #裁剪的右边界
            b: 240 #裁剪的下边界
        }
        resize { #预处理改变大小
            enable: false #开关
            w: 212 #withd像素
            h: 120 #height像素
        }
        permute { #提供给需要通道的转换的场景，默认[0,1,2]为RGB通道顺序，如[2,1,0]则为BGR
            enable: false
            order1: 0
            order2: 1
            order3: 2
        }
    },
    {
        pos: back_left_fisheye
        undistort {
            enable: true
            bal: 1.0
            interp: LINEAR
        }
        crop {
            enable: true
            l: 100
            t: 100
            r: 1820
            b: 1436
        }
        resize {
            enable: false
            w: 1920
            h: 1536
            interp: LINEAR
        }
        permute {
            enable: false
        }
    }
]

hybrid_deploy_config {
  use_cosine_sdk: true
  camera_model: "develop"
}